services:
  web:
    build: .
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./src:/app
    environment:
      - WATCHFILES_FORCE_POLLING=true
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres:16"
    ports:
      - 5432:5432
    env_file:
    - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5